@baseUrl = http://localhost:3000

#RECADOS
###
GET {{baseUrl}}/recados/
?limit=10
&offset=0
Authorization: Bearer 123456
### 
GET {{baseUrl}}/recados/1/
###
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "text": "Cruzeiro ganhou ontem de 2 x 0",
    "deId": 3,
    "paraId":1
}
###
PATCH {{baseUrl}}/recados/10/
Content-Type: application/json

{
    "text": "Teste ALOU",
    "lido": true
}
###
DELETE {{baseUrl}}/recados/8




#PESSOAS 
###
GET {{baseUrl}}/pessoa/
?limit=10
&offset=10
### 
GET {{baseUrl}}/pessoa/1/
###
POST {{baseUrl}}/pessoa
Content-Type: application/json


{
  "email": "fredsion@example.com",
  "password": "minhaSenha123",
   "nome": "Usuário Teste"
}


###
PATCH {{baseUrl}}/pessoa/1/
Content-Type: application/json

{
    "nome": "alef",
    "password": "minhaSenhaNova2"

}
###
DELETE {{baseUrl}}/pessoa/2


#AUTH
###
POST {{baseUrl}}/auth/
Content-Type: application/json

{
    "email": "emaildovictor@gmail.com",
    "password": "senhadovictor"
}

