@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}

#RECADOS
###
GET {{baseUrl}}/recados/
?limit=10
&offset=0
Authorization: Bearer {{authToken}}
### 
GET {{baseUrl}}/recados/1/
###
POST {{baseUrl}}/recados/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "text": "Cruzeiro vai ganhar a CB e brasileirao",
    "paraId":1
}
###
PATCH {{baseUrl}}/recados/2/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "text": "Teste ALOU",
    "lido": true
}
###
DELETE {{baseUrl}}/recados/2
Authorization: Bearer {{authToken}}




#PESSOAS 
###
GET {{baseUrl}}/pessoa/
Authorization: bearer {{authToken}}
### 
GET {{baseUrl}}/pessoa/1/
###
POST {{baseUrl}}/pessoa
Content-Type: application/json

{
  "email": "wallef@gmail.com",
  "password": "senhadovictor",
   "nome": "drive"
}


###
PATCH {{baseUrl}}/pessoa/3/
Content-Type: application/json
Authorization: bearer {{authToken}}

{
    "nome": "wallef",
    "password": "minhaSenhaNova2"

}
###
DELETE {{baseUrl}}/pessoa/1
Authorization: bearer {{authToken}}


#AUTH
### Autenticacao
# @name authenticate

POST {{baseUrl}}/auth/
Content-Type: application/json

{
    "email": "wallef@gmail.com",
    "password": "senhadovictor"
}

