@baseUrl = http://localhost:3000

#RECADOS
###
GET {{baseUrl}}/recados/
?limit=10
&offset=0
Authorization: Bearer 123456
### 
GET {{baseUrl}}/recados/1/
###
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "text": "Cruzeiro vai ganhar a CB",
    "deId": 3,
    "paraId":1
}
###
PATCH {{baseUrl}}/recados/10/
Content-Type: application/json

{
    "text": "Teste ALOU",
    "lido": true
}
###
DELETE {{baseUrl}}/recados/8




#PESSOAS 
###
GET {{baseUrl}}/pessoa/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiZW1haWxkb3ZpY3RvckBlbWFpbC5jb20iLCJpYXQiOjE3NTY5MjA0NTMsImV4cCI6MTc1NjkyNDA1MywiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.8CB2CyABlQvl1RbIZPHPuiocUsT75aHX1TYYIF__tgU
### 
GET {{baseUrl}}/pessoa/1/
###
POST {{baseUrl}}/pessoa
Content-Type: application/json

{
  "email": "emaildovictor@gmail.com",
  "password": "senhadovictor",
   "nome": "victor"
}


###
PATCH {{baseUrl}}/pessoa/1/
Content-Type: application/json

{
    "nome": "alef",
    "password": "minhaSenhaNova2"

}
###
DELETE {{baseUrl}}/pessoa/4


#AUTH
###
POST {{baseUrl}}/auth/
Content-Type: application/json

{
    "email": "emaildovictor@email.com",
    "password": "senhadovictor"
}

